# Change these first
owner: Tiamat-Tech
repo: uptime
user-agent: 0-vortex

# Add your sites here
sites:
  - name: Tiamat Tech
    url: https://tiamat.tech
  - name: Vortex Digital Garden
    url: https://vortex.name
  - name: Vortex Tutorials Domain
    url: https://avortex.online
  - name: Robert Bratucu Blog
    url: https://drbratucu.ro
  - name: Corina Topor Blog
    url: https://corinatopor.com
  - name: Secret i18n Domain
    url: $SECRET_SITE

status-website:
  cname: uptime.tiamat.tech
  theme: dark
  logoUrl: https://img.stackshare.io/company/34440/default_afe1b1a84e1ee87d98822b17478fba7fe0d89334.png
  name: Tiamat Tech uptime monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/Tiamat-Tech/uptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: "@0-vortex"
      href: https://github.com/0-vortex
  commitMessages:
    commitAuthorName: "0-vortex"
    commitAuthorEmail: "237133+0-vortex@users.noreply.github.com"

assignees:
  - 0-vortex
